version: 2.1
workflows:
  version: 2
  scheduled:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - pokemon
jobs:
  pokemon:
    docker:
      - image: node:alpine
    steps:
      - checkout
      - run: npm install
      - run: POKEMON_CODE=571267206266 npm run start
      - run: POKEMON_CODE=392549737526 npm run start
